version: '3.7'
services:
  jenkins:
    image: knmkonexion/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins-master
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock